name: 'Await a workflow execution'
inputs:
  workflowName:
    required: false
    default: ''
    description: >
      A workflow name of the execution target.  
      By the default, all runs are targeted.
  repos:
    required: false
    default: ${{ github.repository }}
    description: >
      Target repository, the format is [owner]/[repository].
  token:
    required: false
    default: ${{ github.token }}
    description: >
      Authorization token such as a github_token or PAT.
  timeoutSec:
    required: false
    default: 180
    description: >
      Timeout secounds of total execution time.
  intervalSec:
    required: false
    default: 3
    description: >
      Interval secounds of call API, the call not containes retry.
runs:
  using: 'node12'
  main: 'dist/index.js'
