name: 'Await a workflow execution'
inputs:
  workflowName:
    required: false
    default: ''
    description: >
      A workflow name of the execution target.
  awaitStartFlag:
    required: false
    default: ''
    description: >
      If input anything in this flag, await a workflow execution to start instead of completion.
  startStatus:
    required: false
    default: 'in_progress'
    description: >
      Define the start meaning, it is [queued] or [in_progress].
      If awaitStartFlag is false, this argument is ignored.
  repos:
    required: false
    default: ${{ github.repository }}
    description: >
      Target repository, the format is [owner]/[repository].
  token:
    required: false
    default: ${{ github.token }}
    description: >
      Authorization token such as a github_token or PAT.
  timeoutSec:
    required: false
    default: 180
    description: >
      Timeout secounds of total execution time.
runs:
  using: 'node12'
  main: 'dist/index.js'
