name: 'Await workflow runs'
description: 'Wait for workflow runs to complete.'

inputs:
  workflowName:
    required: false
    default: ''
    description: >
      A workflow name of the targets that make wait.  
      By the default, all runs are targeted.
  repos:
    required: false
    default: ${{ github.repository }}
    description: >
      Target repository, the format is [owner]/[repository].
  token:
    required: false
    default: ${{ github.token }}
    description: >
      Authorization token such as a github_token or PAT.
  timeoutSec:
    required: false
    default: 600
    description: >
      Timeout secounds of total execution time.
  intervalSec:
    required: false
    default: 3
    description: >
      Interval secounds of call API, the call not containes retry.
  numOfRef:
    required: false
    default: 30
    description: >
      The number of references when acquiring the wait targets.
      This is referenced in order from newest runs.

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'anchor'
  color: 'red'