name: 'Await workflow completions'
inputs:
  workflowName:
    required: false
    default: ''
  repos:
    required: false
    default: ${{ github.repository }}
  token:
    required: false
    default: ${{ github.token }}
  timeoutSec:
    required: false
    default: 120
runs:
  using: 'node12'
  main: 'dist/index.js'
